version: '2'

services:

    mysql:
        container_name: mysql
        image: daocloud.io/library/mysql
        restart: always
        expose:
            - "3306"
        ports: 
            - "3306:3306"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ~/data/docker_data/mysql_3306/data:/data
            - ~/data/docker_data/mysql_3306/var-lib-mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
        restart: always

    php-fpm:
        container_name: php-fpm
        build: ./PHP7.1/
        restart: always
        expose:
            - "9000"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ~/data/docker_data/php-fpm_9000:/data
        links:
            - mysql:mysql

    nginx:
        container_name: nginx
        build: ./OpenResty/
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ~/data/docker_data/nginx_80_443/conf.d:/etc/nginx/conf.d
        volumes_from:
            - php-fpm
        links:
            - mysql:mysql
            - php-fpm:php-fpm
