version: '3.7'

services:

  splash:
    image: scrapinghub/splash:3.4
    command: --maxrss 2048 --max-timeout 300 --disable-lua-sandbox --verbosity 1
    ports:
      - "8050:8050"
    volumes:
      - ./data/filters:/etc/splash/filters
      - ./data/js-profiles:/etc/splash/js-profiles
      - ./data/lua_modules:/etc/splash/lua_modules
      - ./data/proxy-profiles:/etc/splash/proxy-profiles
    restart: unless-stopped
